command_timeout = 2000

[aws]
disabled = true

[gcloud]
disabled = true

[azure]
disabled = true

[nodejs]
disabled = true

[package]
disabled = true

[mise]
disabled = false
healthy_symbol = 'ðŸŸ¢'
unhealthy_symbol = 'ðŸ”´'

[custom.localmail]
command = "grep -c '^From ' /var/mail/$USER 2>/dev/null || echo 0"
when = "test -s /var/mail/$USER"
symbol = "ðŸ“¬ "
format = "[$symbol$output]($style) "
style = "bold yellow"

[cmd_duration]
min_time = 500
