# Mac App Store applications managed via mas CLI
# App IDs can be found by running: mas list

mas_apps:
  682658836: GarageBand
  408981434: iMovie
  409183694: Keynote
  409203825: Numbers
  409201541: Pages
  1303222628: Paprika Recipe Manager 3
  1289583905: Pixelmator Pro
  1039633667: Irvue
