brew:
  packages:
    - zoxide
    - bat
    - gh
    - rust
    - mise
    - fish
    - fontconfig
    - libyaml
    - coreutils
    - starship

  casks:
    - nikitabobko/tap/aerospace
    - github
    - visual-studio-code
    - raycast
    - keycastr
    - ghostty
    - orbstack
    - dropbox
    - cursor

applications:
  - name: 1Password
    path: /Applications/1Password.app
    brew_cask: 1password
    cli_tap: 1password/tap/1password-cli

  - name: Arc
    path: /Applications/Arc.app
    brew_cask: arc
