brew:
  packages:
    - zoxide
    - bat
    - gh
    - rust
    - mise
    - fish
    - fontconfig
    - libyaml
    - coreutils
    - starship

  casks:
    - nikitabobko/tap/aerospace
    - cursor
    - discord
    - dropbox
    - ghostty
    - github
    - keycastr
    - obsidian
    - orbstack
    - raycast
    - slack
    - steam
    - telegram
    - visual-studio-code
    - whatsapp
    - zoom

applications:
  - name: 1Password
    path: /Applications/1Password.app
    brew_cask: 1password
    cli_tap: 1password/tap/1password-cli

  - name: Arc
    path: /Applications/Arc.app
    brew_cask: arc
