[tools]
ruby = "latest"
node = "lts"
go = "latest"
rust = "latest"
"cargo:broot" = "latest"
"cargo:difftastic" = "latest"
"cargo:starship" = "latest"
"npm:@openai/codex" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"go:github.com/mikefarah/yq/v4" = "latest"
watchexec = "latest"
fnox = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
legacy_version_file = true
experimental = true
