[tools]
ruby = "latest"
node = "lts"
go = "latest"
rust = "latest"
"cargo:broot" = "latest"
"cargo:difftastic" = "latest"
"cargo:starship" = "latest"
"gem:try-cli" = "latest"
"npm:@openai/codex" = "latest"
"npm:@anthropic-ai/claude-code" = "latest"
"go:github.com/mikefarah/yq/v4" = "latest"
"go:github.com/noperator/yknotify" = "latest"
watchexec = "latest"
fnox = "latest"
fzf = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
legacy_version_file = true
experimental = true
fetch_remote_versions_cache = "7d"
http_timeout = "5s"
fetch_remote_versions_timeout = "5s"

[env]
CARGO_HTTP_TIMEOUT = "5"
GO_GET_TIMEOUT = "5s"
