[tools]
ruby = "latest"
node = "lts"
go = "latest"
watchexec = "latest"
fnox = "latest"

[settings]
idiomatic_version_file_enable_tools = ["ruby", "node"]
legacy_version_file = true
experimental = true
